spring:
  profiles:
    include: secret

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  logging:
    level:
      org:
        hibernate:
          SQL: debug