blank_issues_enabled: false

issue_template:
  - name: "🐞 Fix"
    description: "버그 수정 템플릿을 사용하여 문제를 보고하세요."
    labels: ["fix"]
    file: fix.yml
  - name: "✨ Feature"
    description: "새로운 기능 추가를 제안하거나 구현할 때 사용하세요."
    labels: ["feature"]
    file: feature.yml
  - name: "🔧 Refactor"
    description: "기능 변경 없이 코드 개선이 필요할 때 사용하세요."
    labels: ["refactor"]
    file: refactor.yml
  - name: "✏️ Docs"
    description: "문서화 작업이 필요할 때 사용하세요."
    labels: ["docs"]
    file: docs.yml
