name: "✨ Feature"
description: "새로운 기능 추가 (제목은 '[Feat] 소셜 로그인 추가' 형태로 입력해 주세요)"
title: "[Feat] "
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: |
        새로운 기능에 대한 설명을 작성해 주세요.
        예: 소셜 로그인(Google, Naver)을 통해 계정 생성 및 인증 가능하도록 구현
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: |
        할 일을 체크박스 형태로 작성해주세요.
        예:
        - [ ] OAuth2 로그인 설정 추가
        - [ ] 프론트엔드 로그인 버튼 구현
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: |
        참고 자료가 있다면 작성해 주세요.
        예:
        - OAuth2 공식 문서
        - 유사 기능을 다룬 블로그 글
        - 디자인 시안 링크
        참고 자료가 없는 경우 `_No response_`로 작성해 주세요.
