name: "🐞 Fix"
description: "버그 수정 (제목은 '[Fix] 로그인 에러 발생' 형태로 입력해 주세요)"
title: "[Fix] "
labels: ["fix"]
body:
  - type: textarea
    attributes:
      label: 🔍 기능
      description: |
        어느 기능에서 버그가 발생했는지 작성해 주세요.
        예: 로그인 시도 후 화면 전환 실패
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 설명
      description: |
        발생한 버그에 대한 설명을 작성해 주세요.
        예: 로그인 버튼 클릭 시 500 에러 발생, 서버 응답 없음
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: |
        수정할 일을 체크박스 형태로 작성해주세요.
        예:
        - [ ] 로그인 API 응답 형식 확인
        - [ ] 예외 처리 로직 추가
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: |
        참고 자료가 있다면 작성해 주세요.
        예:
        - 관련 에러 로그
        - 스택 오버플로우 링크
        - 관련 코드 스니펫
        참고 자료가 없는 경우 `_No response_`로 작성해 주세요.
